### PR TITLE
Improved the service behaviour, error messages, and unit tests

### PR DESCRIPTION
**Pull request by k0pernicus**
Hi,

I do not really know the purpose of this service so feel free to reject if my propositions are not useful :)

I made multiple contributions here:  
1. Improved the code in creating special functions to write on ResponseWriter structures;
2. Added `return` statement after error response (otherwise we can write multiple responses on the same ResponseWriter);
3. Added distinction between **internal** service errors and errors we can return to the user;
4. Added a `pkg` package in order to let people use the errors in their own service (if they want to call and check the service output for example);
5. Improved and added new unit tests (especially for the go trick + Record comparisons).

### CODE REVIEW

**Review by arnaudmorisset — DISMISSED** [review]
Hi!

Thanks a lot for the contribution, that's a nice PR. 😯 

EDIT: `go vet` saw an unused error. 🙂

**Comment by k0pernicus** [comment]
@arnaudmorisset Thanks - I forgot to run it before the latest submission, my bad :)

**Review by arnaudmorisset — APPROVED** [review]
Thanks again! 🙂

**Comment by k0pernicus** [comment]
My pleasure :)

**Pull request merged**
